steps:
        - name: 'gcr.io/cloud-builders/docker'
          id: Build
          args:
                  - 'build'
                  - '-t'
                  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
                  - 'src/go/.'
        - name: 'gcr.io/cloud-builders/docker'
          id: Push
          args:
                  - 'push'
                  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
        - name: 'gcr.io/cloud-builders/kubectl'
          id: Deploy
          args:
                  - 'apply'
                  - '-f'
                  - 'deployment.yaml'
          env:
                  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
                  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'
